# Generated by Django 5.0 on 2024-09-29 07:24

import autoslug.fields
import store.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_favouriteitem_product_alter_favouriteitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, populate_from='name', slugify=store.models.custom_slugify),
            preserve_default=False,
        ),
    ]
