# Generated by Django 5.0 on 2024-10-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'В обработке'), ('C', 'Завершен'), ('F', 'Отменен'), ('S', 'Отправлен'), ('D', 'Доставлен')], default='P', max_length=1, verbose_name='статус'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10, verbose_name='цена за единицу'),
            preserve_default=False,
        ),
    ]
