version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "
      until nc -z db 5432; do
        echo 'Waiting for the database...';
        sleep 1;
      done;
      python manage.py migrate &&
      python manage.py csu &&
      echo 'Visit the site at http://localhost:8000' &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"

  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"

  celery:
    build:
      context: .
    command: celery -A config worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
